/*
        OPERADORES ARITIMÉTICOS
        + (SOMAR)
        - (SUBTRAIR)
        * (MULTIPLICAR)
        / (DIVIDIR)
       %(MODULO) = RESTO DA DIVISAO
*/ 
        SELECT 1 + 1 AS ADICAO
        SELECT 5 - 10 AS [SUBTRACAO(-1)]
        SELECT (2 + 7) * 10 AS MULTIPLICACAO
        SELECT 90 / 3 AS DIVISAO
        SELECT 90 / 60 AS DIV2
        SELECT 90 % 60 AS [RESTO DA DIVISAO]

        SELECT 1 + '1' AS SOMA
        SELECT '1' + '1' AS SOMA_STRING -- SINAL DE SOMA COM TEXTOS SERÁ UMA CONCATENAÇÃO
        SELECT 'Joao' + ' Pedro' SOMA_STRING